# -*- coding: utf-8 -*-
"""OOP3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L947hY8-5D3WQsApZT7vAKne_w2B9IDo
"""

class Shape(object):
  def __init__(self):
    self._position = ''
    self._scale = ''
    self._color = ''

  def set_position(self, position):
    self._position = position

  def get_position(self):
    return self._position

  def set_scale(self, scale):
    self._scale = scale

  def get_scale(self):
    return self._scale

  def set_color(self, color):
    self._color = color

  def get_color(self):
    return self._color


  def info(self):
    print(f'Координаты: {self._position}, Размер: {self._scale}, Цвет: {self._color}')

class Rectangle(Shape):
  def __init__(self):
    super().__init__()
    self._side1 = ''
    self._side2 = ''
    
  def set_side1(self, side1):
    self._side1 = side1
      
  def get_side1(self):
    return self._side1
        
  def set_side2(self, side2):
    self._side2 = side2
        
  def get_side2(self):
    return self._side2

  def info(self):

    super().info()
    print(f'Сторона 1: {self._side1}, Сторона2: {self._side2}')

math = Rectangle()
math.set_position(10)
math.set_scale(15)
math.set_color("Красный")
math.set_side1(5)
math.set_side2(5)

